[build.environment]
  NPM_FLAGS = "--version" # prevent Netlify npm install
[build]
  command = 'npx pnpm i --store=node_modules/.pnpm-store && npm run build'
  publish = 'dist'

[[redirects]]
  from = "/posts/*"
  to = "https://malcolmkee.com/blog/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/"
  to = "https://malcolmkee.com/blog/"
  status = 301
  force = true